name = "sla-monitoring-api"
main = "src/index.ts"
compatibility_date = "2025-09-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "sla-monitoring"
database_id = "0d085522-8493-4491-a7c3-1b1932ce46be"
